FROM quay.io/pypa/manylinux2014_x86_64

RUN yum update && yum install -y binutils
RUN /opt/python/cp37-cp37m/bin/pip install cython wheel && \
        /opt/python/cp38-cp38/bin/pip install cython wheel && \
        /opt/python/cp39-cp39/bin/pip install cython wheel

ENV DEBUG_LEVEL=0